import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import BlogPost from "../components/BlogCard";
import Header from "../components/Header";
import Footer from "../components/Footer";

const graphcms = new GraphQLClient(process.env.GRAPHCMS);

const MyQuery = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(MyQuery);

  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>FumiMelvin GraphCMS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="">
        {posts.map((post) => (
          <BlogPost
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
      </main>
      <Footer />
    </>
  );
}
